[package]
name = "perch"
version = "0.1.0"
authors = ["thsowers <tyler@startrakstudios.com>"]
edition = "2018"

[dependencies]
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
clap = "2.32.0"
tantivy = "0.8.2"